version: '3'

services:
  db_pco:
    image: postgres:15
    environment:
      POSTGRES_USER: "pco"
      POSTGRES_PASSWORD: "pco"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
      - pco_sql:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    restart: on-failure

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pco_sql:
